---
abstract: 'Catalyst based picture gallery'
author:
  - 'Luke Ross'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lemon
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::I18N::Request: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.80013
  Catalyst::View::TT: 0
  Config::General: 0
  DateTime: 0
  Digest::SHA1: 0
  GD: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
